name: Publish

on:
  release:
    types: [published]

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile -t pdnsbackup

    - name: Tag image
      run: |
        docker tag pdnsbackup dmachard/pdnsbackup:${{ github.event.release.tag_name }}
        docker tag pdnsbackup dmachard/pdnsbackup:latest

    - name: Upload to DockerHub
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_LOGIN }}" --password-stdin
        docker push dmachard/pdnsbackup:latest
        docker push dmachard/pdnsbackup:${{ github.event.release.tag_name }}

  pypi:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install twine jinja2

    - id: pkg_version
      run: echo "data=$(echo ${{ github.event.release.tag_name }} | cut -c2-)" >> $GITHUB_OUTPUT

    - name: Build Python package
      run: |
        python -c 'import jinja2;jinja2.Template(open("setup.j2").read()).stream(version="${{ steps.pkg_version.outputs.data }}").dump("setup.py")'
        python setup.py sdist bdist_wheel

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
