name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  unittests:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python: [ "3.11" ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python}}

    - name: Run Python tests
      run: |
        sudo python --version
        sudo python -m pip install -r requirements.txt
        sudo python -m unittest -v tests.test_config
        sudo python -m unittest -v tests.test_parser
        sudo python -m unittest -v tests.test_export

  integration:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        pdns-version: [ "48" ]
        python: [ '3.11' ]
        include:
        - pdns-version: "48"
          branch: "auth-4.8.x"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Setup MariaDB
        run: |
          sudo docker run -d --network="host" --name mariadb -e MARIADB_ROOT_PASSWORD=pdns -e MARIADB_DATABASE=pdns -e MARIADB_USER=pdns -e MARIADB_PASSWORD=pdns mariadb:latest
          sudo docker exec -i mariadb sh -c 'exec mariadb-admin ping -h 127.0.0.1 -u root --password=pdns --wait=30'
    
      - name: Import sql schema
        run: |
          sudo wget https://raw.githubusercontent.com/PowerDNS/pdns/rel/${{ matrix.branch }}/modules/gmysqlbackend/schema.mysql.sql
          sudo docker exec -i mariadb sh -c 'exec mariadb -u root -p"pdns" pdns' < schema.mysql.sql

      - name: Setup PowerDNS
        run: |
          sudo docker run -d --network="host" --name powerdns --volume=$PWD/tests/pdns.conf:/etc/powerdns/pdns.conf:ro --volume=$PWD/tests/db.example.com:/var/lib/powerdns/db.example.com:ro --volume=$PWD/tests/db.0.10.in-addr.arpa:/var/lib/powerdns/db.0.10.in-addr.arpa:ro powerdns/pdns-auth-${{ matrix.pdns-version }}:latest
          sudo docker logs powerdns
          sudo chmod +x ./tests/initzone.sh
          sudo ./tests/initzone.sh

      - name: Run Python tests 
        run: |
          python --version
          sudo python -m pip install -r requirements.txt 
          sudo python -m unittest tests.test_import -v

      - name: Check zone format
        run: |
          sudo apt-get update && sudo apt-get install -y bind9utils
          sudo named-checkzone example.com /tmp/pdnsbackup/db.example.com
          sudo named-checkzone 0.10.in-addr.arpa /tmp/pdnsbackup/db.0.10.in-addr.arpa

      - name: Check bind named config
        run: |
          sudo cat /tmp/pdnsbackup/named.conf
          sudo named-checkconf /tmp/pdnsbackup/named.conf