name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python: [ "3.11" ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python}}

    - name: Run Python tests
      run: |
        python --version
        python -m pip install -r requirements.txt
        python -m unittest -v tests.test_config
        python -m unittest -v tests.test_parser
        python -m unittest -v tests.test_export